<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password</name>
   <tag></tag>
   <elementGuidId>86a954a7-f993-4d38-860a-fa749963ed3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPassword']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;divPassword&quot;)/span[@class=&quot;form-hint&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#divPassword > span.form-hint</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>123c7283-c52e-44da-addf-e89d4e69d6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-hint</value>
      <webElementGuid>f5357feb-ae2b-4143-9028-e57a80ae4246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>07d94227-839a-4a96-9026-49d9a7c1d6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divPassword&quot;)/span[@class=&quot;form-hint&quot;]</value>
      <webElementGuid>c4409dd3-7906-4949-82a6-3ac003460f02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//input[@id='txtPassword']</value>
      <webElementGuid>3905e01c-ab8e-4b9d-8918-92a63cf37120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
